-- lv.4
WITH TOP_REVIEWER AS (
    SELECT MEMBER_ID, COUNT(*)
    FROM REST_REVIEW r 
    GROUP BY MEMBER_ID
    ORDER BY 2 DESC
    LIMIT 1
)

SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE m
    JOIN TOP_REVIEWER t
    JOIN REST_REVIEW r
WHERE t.MEMBER_ID = m.MEMBER_ID AND r.MEMBER_ID = m.MEMBER_ID
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT;
