--  둘 다 정답
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER 
FROM FIRST_HALF, ICECREAM_INFO WHERE ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
GROUP BY ICECREAM_INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER 
FROM FIRST_HALF INNER JOIN ICECREAM_INFO ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;